name: ARM64 Docker 真机
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  arm64-docker:
    runs-on: ubuntu-24.04-arm64   # 真 ARM64（aarch64）
    steps:
      - name: 查看架构
        run: uname -m

      - name: 查看 Docker 版本
        run: docker --version
